### ISSUE TITLE
Crashes when no more human  moves

### ISSUE THREAD

**Issue by morana21** [baldwinn20/BlokusGame#11]
Play until human player cannot move anymore, image attached 
...
Game cannot move forward since human player is stuck on their turn
![20190415_152628](https://user-images.githubusercontent.com/46700898/56169431-ee562e00-5f92-11e9-865e-222a4c15b09e.jpg)

**Comment by Pichu123** [comment]
Thanks for telling us! We added a Give Up button so the human player can decide whether or not they can make any more legal moves.

**Comment by morana21** [comment]
fixed: give up button skips players turn
