### ISSUE TITLE
Place pieces when not your turn, they disappear from inventory

### ISSUE THREAD

**Issue by torkelso19** [baldwinn20/BlokusGame#12]
Step 1: Setup game with 2 blue AI instead of a yellow
Step 2: While its waiting for yellow to move (always), place pieces and they get removed from inventory and disappear

**Comment by Pichu123** [comment]
Thank you for telling us! We removed the player colors from the config screen so it is based on types of AI instead (dumb or smart). We disabled the human GUI when it isn't their turn so pieces won't disappear.

**Comment by torkelso19** [comment]
This has been fixed, now it is just a general dumb AI or smart AI instead of each color!
