### ISSUE TITLE
Multiple AI's of the same color

### ISSUE THREAD

**Issue by nelsons19** [baldwinn20/BlokusGame#13]
Steps:
1) when starting the game enter at least two AI's of the same color
2) Try and play
3) Unable to play when it reaches removed AI color's turn
    -i.e. If I replace a yellow dumb AI with a second dumb Blue no one is able to play when it should be yellows turn

**Comment by baldwinn20** [comment]
We removed color names from the config menu so this cannot happen.

**Comment by nelsons19** [comment]
I like the fix, great job!
