### ISSUE TITLE
GUI Grid Shifts

### ISSUE THREAD

**Issue by AverageGatsby98** [baldwinn20/BlokusGame#14]
(This is Spencer Rose)

Bug: when you first touch the grid to move your tile around the whole grid shifts downwards and the pieces on the bottom and right of the grid can be dragged partially off screen

**Comment by Pichu123** [comment]
Thanks for telling us! Dylan set the message box to be a fixed height so it wouldn't shift anymore.

**Comment by AverageGatsby98** [comment]
I checked and this it was fixed!
