### ISSUE TITLE
If human player isn't first in config list, pieces all disappear when placing

### ISSUE THREAD

**Issue by torkelso19** [baldwinn20/BlokusGame#15]
Step 1: Change config to make the human player not first
Step 2: Start game and can't place anything

**Comment by Pichu123** [comment]
Thanks for telling us! We were able to fix this by using playerNum to get the correct indexes so we no longer needed to pass in a color when making a new instance of a player in the main activity.

**Comment by torkelso19** [comment]
This has been fixed and the human player can now change colors
