### ISSUE TITLE
Pressing a placed tile increments the player's score

### ISSUE THREAD

**Issue by hoser21** [baldwinn20/BlokusGame#2]
Steps to recreate:
1. Place a tile in the red corner
2. Place another tile diagonally one box down and one box right
3. Click the previous tile that was placed in step two.
-----
After the third step, the score should not increment again since the tile was already placed.

**Comment by baldwinn20** [comment]
Essentially the same issue as #4- see #4

**Comment by hoser21** [comment]
Thanks! It looks fixed now.
