### ISSUE TITLE
Game crashes when user touches edge of board. 

### ISSUE THREAD

**Issue by marcial21** [baldwinn20/BlokusGame#3]
Steps to Recreate:
1. Run the game.
2. Click on end of the board edge piece. 

The game crashes when user clicks at the end of the board. Unlike other places in the board, it should notify the user with the message "Invalid Touch, out of bounds" since it appears in other places. However, in this case, the game crashes.

**Comment by Pichu123** [comment]
Thanks for telling us! We fixed the edge cases for the board and the player no longer needs to touch on a tile to try and place a piece, they can now drag their piece across the board.

**Comment by marcial21** [comment]
Awesome! I have verified this.
