### ISSUE TITLE
Number of Pieces Left falls below 0

### ISSUE THREAD

**Issue by LozinALaifer** [baldwinn20/BlokusGame#4]
Steps to recreate:
1. Run Game
2. Placed numerous blocks into the board

...

The number of pieces left goes into the negatives which does not reflect really how much pieces a player has left.

**Comment by Pichu123** [comment]
Thanks for telling us! When the local game checks if the game is over, if a player has no more pieces remaining, they win the game.

**Comment by LozinALaifer** [comment]
Alright, looks like the number of pieces left is reflected nicely! Great job guys!
