### ISSUE TITLE
Smart AI Implementation Recommendation

### ISSUE THREAD

**Issue by slemly** [baldwinn20/BlokusGame#8]
Currently no smart AI is implemented.
Suggestions for this implementation could be: 
--assign each piece a weight based upon how many tiles compose it, then have the bot look for the piece with the highest weight
--Weight could be modified by the perimeter of the piece (the plus sign or similar awkward pieces might have different weights than straight lines or the square-plus-one piece)
--Pieces could try to be placed so that slope(coordinates of last piece, center of the board) gets to zero, meaning the bot would try to make it to the middle of the board as fast as possible

**Comment by Pichu123** [comment]
Thanks for the suggestion! We decided to make our Smart AI's place their biggest pieces first so as the board gets more crowded later on, they will be less likely to give up making moves.

**Comment by slemly** [comment]
I like the workaround! It is intuitive and similar to what I had in mind.
