### ISSUE TITLE
Help Button Doesn't Work 

### ISSUE THREAD

**Issue by campbeld21** [baldwinn20/BlokusGame#9]
Steps to Recreate:
1. Open the app
2. Start the game 
3. Press the help button

Suggestions:
- implement an onclicklistener like all of the other buttons and give it an action to perform when pressed i.e. drop down a help menu

**Comment by Pichu123** [comment]
Thanks for the suggestion! We made a separate activity for the help button to display all the rules and return back to the game with an onclicklistener.

**Comment by campbeld21** [comment]
They fixed the issue, great work!
